### ISSUE TITLE
Run on Nativescript Angular 3.0

### ISSUE THREAD

**Issue by mrubkey** [NathanWalker/nativescript-shimmer#2]
Hi! @NathanWalker 
I need your help for my project with Shimmer plugin.
How to config this plugin run on  Nativescript Angular 3.0

**Comment by NathanWalker** [comment]
Hi @mrubkey version `2.0.0` published now supports {N} 3.0 and Angular.
You can see example Angular usage in the `demo-ng` here:
https://github.com/NathanWalker/nativescript-shimmer/tree/master/demo-ng/app

**Comment by ghost** [comment]
@NathanWalker im having trouble running the angular demo cause there's an error saying `com.facebook.shimmer.ShimmerFrameLayout is not a constructor`

**Comment by e-burlaka-md** [comment]
@jannotabamo i had the same problem, but after reinstalling plugin it started working
